### ISSUE TITLE
How to pass spring properties into the config file

### ISSUE THREAD

**Issue by ltebean** [akihyro/logback-access-spring-boot-starter#23]

**Comment by akihyro** [comment]
Thanks for report.

The feature to reference the Spring property from the config file is not currently supported.
I'd like to support in future versions.

**Comment by akihyro** [comment]
I have released the `<springProperty>` tag in version 2.5.0.
Please see [README] for usage.

[README]: https://github.com/akihyro/logback-access-spring-boot-starter/blob/master/README.md#springproperty-tag-environment-properties

> ### `<springProperty>` tag: Environment properties
> 
> The `<springProperty>` tag allows you to surface properties from the Spring `Environment`.  
> Usage of this extension follows [Spring Boot Logback extension "Environment properties"].  
> 
> > ```xml
> > <springProperty scope="context" name="fluentHost" source="myapp.fluentd.host" defaultValue="localhost" />
> > <appender name="FLUENT" class="ch.qos.logback.more.appenders.DataFluentAppender">
> >     <remoteHost>${fluentHost}</remoteHost>
> >     ...
> > </appender>
> > ```
> 
> [Spring Boot Logback extension "Environment properties"]: http://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#_environment_properties

Thanks.
