### ISSUE TITLE
Quiet access logging during tests

### ISSUE THREAD

**Issue by binkley** [akihyro/logback-access-spring-boot-starter#24]
I'd like to turn off access logging during testing.  I trust it works, so am not testing it; it's just noise during tests.  I have a `logback-test.xml` which sets `ROOT` level to `WARN`, but that doesn't quiet access logging so that's not it.  I'm also using `runtime` scope in for the dependency in maven, but that's not it either.  Thanks!

So this issue is either 1) documentation, or 2) enhancement.

**Comment by akihyro** [comment]
Thanks for report.
There are the following ways.

- - -

1) Create an empty configuration file for the test.
The configuration file name is `logback-access-test.xml`.

For example: `logback-access-test.xml`

```xml
<configuration />
```

- - -

2) Disable logback-access in the Spring configuration properties.

For example: JUnit test class

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(YourApplication.class)
@WebIntegrationTest(value = "logback.access.enabled=false", randomPort = true)
public class YourTest {
    // ...
}
```

- - -

3) Disable logback-access in the Spring profile.

For example: JUnit test class

```java
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(YourApplication.class)
@ActiveProfiles("test")
public class YourTest {
    // ...
}
```

For example: `application-test.yml`

```yaml
logback.access:
  enabled: false
```

**Comment by binkley** [comment]
Method (1) worked perfectly -- thanks!  So this request becomes one of documentation on the front page.

**Comment by akihyro** [comment]
I have documented it as follows.

https://github.com/akihyro/logback-access-spring-boot-starter/blob/master/README.md

> "logback-access-spring-boot-starter" will look for the configuration file in the following order.  
> The first found configuration file will be used.  
> 
> 1. "logback-access-test.xml" in the root of classpath.
> 2. "logback-access.xml" in the root of classpath.
> 3. fallback configuration file (appends to standard output with common pattern).

**Comment by binkley** [comment]
I like the `README.md`.  Would be possible to have some language in there mentioning that using a separate test XML (or perhaps property in the YAML) would support quieter testing?  I hope this request isn't too specific to my own tastes!  :)

**Comment by binkley** [comment]
Thanks again for the help.  Can this issue be closed?

**Comment by akihyro** [comment]
Sorry for the late reply.

I think that logging configuration for testing is different for each user.
For example, may want to quiet like this time.
For example, may want to output to a another file. etc..
So I do not mention the logging configuration for testing.

If you are OK, you can close it.
