### ISSUE TITLE
Improper use of Apache License

### ISSUE THREAD

**Issue by jvz** [akihyro/logback-access-spring-boot-starter#25]
I was confused as to which license this project used until I noticed the link in the readme. You should include a file called LICENSE (or LICENSE.txt, or COPYING, or COPYING.txt) with the license itself. The license also recommends adding a small header to all your files, but I think that's optional (it does help).

Edit: I should also mention that adding the license file will allow GitHub to autodetect which license you're using.

**Comment by akihyro** [comment]
Thanks for report.

I added LICENSE.txt.

https://github.com/akihyro/logback-access-spring-boot-starter/blob/master/LICENSE.txt

**Comment by jvz** [comment]
Thanks for the clarification!
