### ISSUE TITLE
Consider removing duplicate default value and javadoc tags from configuration key's javadoc 

### ISSUE THREAD

**Issue by snicoll** [akihyro/logback-access-spring-boot-starter#31]
The annotation processor does not handle javadoc tags and they are written as is in the json file. It's not a requirement for IDE to be able to parse this so the output may not be nice (I haven't tried though).

Also, please do not write "Defaults to XYZ" in the documentation since the default value is picked up by the initial value and IDEs display that information when available already. If the metadata does not contain that value the `defaultValue` field in manual metadata is a much better option than in the description.

Finally I understand the convenience but `Optional` is not supported by the annotation processor (and I am not sure the IDE is prepared to handle it). All properties are optional since the feature may not be activated (it's hard to determine this IMO). I am not convinced that storing `Optional` field is a good idea (though you've noticed they have to match the type of the getter/setter for the description to show up. If you have ideas to improve that, feel free to raise an issue.

Thanks!

**Comment by akihyro** [comment]
I hadn't  considered the output of the annotation processor.
Thank you for pointing out the issue.

I fixed it as follows: dc2131b8754637ce2a8b235691dabcd83c0a9f38

* I removed Javadoc tags.
* I removed duplicate descriptions of default values from Javadoc comments.
* I decided not to use Optional.

If you are ok with this, I will release it as the next version!

**Comment by snicoll** [comment]
LGTM

**Comment by akihyro** [comment]
v2.4.0 has been released!

https://github.com/akihyro/logback-access-spring-boot-starter/releases/tag/v2.4.0
