### ISSUE TITLE
Add spring-boot 2 support

### ISSUE THREAD

**Issue by slamdev** [akihyro/logback-access-spring-boot-starter#35]
`EmbeddedServletContainerCustomizer` is replaced by `ConfigurableServletWebServerFactory` in the upcoming spring boot version so the library is not working. It would be nice to support it.

**Comment by akihyro** [comment]
Thanks for report.
I'd like to support in future versions!

**Comment by abatkin** [comment]
See #40

**Comment by akihyro** [comment]
I merged #40 and released [v2.7.0](https://github.com/akihyro/logback-access-spring-boot-starter/releases/tag/v2.7.0).

Thanks!
