### ISSUE TITLE
Version 2.7.0 refers to unreleased libraries

### ISSUE THREAD

**Issue by sebastiankirsch** [akihyro/logback-access-spring-boot-starter#41]
We cannot upgrade to version 2.7.0:

    [ERROR] Failed to execute goal on project test-accesslog: Could not resolve dependencies for project de.tcc:test-accesslog:jar:1.0-SNAPSHOT: Failed to collect dependencies at net.rakugakibox.spring.boot:logback-access-spring-boot-starter:jar:2.7.0: Failed to read artifact descriptor for net.rakugakibox.spring.boot:logback-access-spring-boot-starter:jar:2.7.0: Failure to find io.projectreactor:reactor-bom:pom:Bismuth-M3

The mentioned library, `io.projectreactor:reactor-bom:pom:Bismuth-M3`, is [not accessible via maven repo](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.projectreactor%22%20AND%20a%3A%22reactor-bom%22).  
I assume though that this is a consequential error, since `org.springframework.boot:spring-boot-starter-parent:2.0.0.M3` doesn't exist in the Maven repo either.

I guess building `logback-access-spring-boot-starter` works because of the recently added `repositories` section in the POM file; but this doesn't propagate if `logback-access-spring-boot-starter` is simply used by another project.

**Comment by sebastiankirsch** [comment]
I'd also kindly suggest to do a major release once you switch to Spring Boot 2.x

**Comment by abatkin** [comment]
You want to use the [v2.6.x branch](https://github.com/akihyro/logback-access-spring-boot-starter/tree/v2.6.x) until Spring Boot 2.0 is released - 2.7.x and above are for the as-yet-unreleased Spring Boot 2.0.
