### ISSUE TITLE
%{XXXX}r or %{XXXX}i not supported

### ISSUE THREAD

**Issue by zhangxh0517** [akihyro/logback-access-spring-boot-starter#52]
Only support % D, % r..... ,    %{XXXX}r not supported?

**Comment by chentging** [comment]
Hi gays, use %requestAttribute{xxxx} will get beautful life! 

**Comment by zhangxh0517** [comment]
> Hi gays, use %requestAttribute{xxxx} will get beautful life! �

You are 6666
